// @flow

export const ZUNDOKO_BUTTON_CLICKED = 'ZUNDOKO_BUTTON_CLICKED';
export const ZUNDOKO_FETCH_SUCCEEDED = 'ZUNDOKO_FETCH_SUCCEEDED';
export const ZUNDOKO_FETCH_FAILED = 'ZUNDOKO_FETCH_FAILED';
export const KIYOSHIED = 'KIYOSHIED';
